### ISSUE TITLE
Update to latest unreal version

### ISSUE THREAD

**Issue by avikbis** [ProjectBorealis/RTXGI-UE-Plugin#1]
This unfortunately do not work with 5.4

```
0>[5/12] Compile [x64] DDGIVolumeUpdate.cpp
0>DDGIVolumeUpdate.cpp(219): Error C2065 : 'FRaytracingLightDataPacked': undeclared identifier
0>DDGIVolumeUpdate.cpp(219): Error C2923 : 'TRDGUniformBufferBinding': 'FRaytracingLightDataPacked' is not a valid template type argument for parameter 'TBufferStruct'
0>DDGIVolumeUpdate.cpp(219): Reference  : see declaration of 'FRaytracingLightDataPacked'
0>DDGIVolumeUpdate.cpp(219): Error C3203 : 'TRDGUniformBufferBinding': unspecialized class template can't be used as a template argument for template parameter 'TypeParameter', expected a real type
0>DDGIVolumeUpdate.cpp(280): Error C2065 : 'FRaytracingLightDataPacked': undeclared identifier
0>DDGIVolumeUpdate.cpp(280): Error C2923 : 'TRDGUniformBufferBinding': 'FRaytracingLightDataPacked' is not a valid template type argument for parameter 'TBufferStruct'
0>DDGIVolumeUpdate.cpp(280): Reference  : see declaration of 'FRaytracingLightDataPacked'
0>DDGIVolumeUpdate.cpp(280): Error C3203 : 'TRDGUniformBufferBinding': unspecialized class template can't be used as a template argument for template parameter 'TypeParameter', expected a real type
0>DDGIVolumeUpdate.cpp(880): Error C2039 : 'RayTracingLightDataUniformBuffer': is not a member of 'FViewInfo'
0>DDGIVolumeComponent.h(32): Reference  : see declaration of 'FViewInfo'
0>DDGIVolumeUpdate.cpp(1017): Error C2039 : 'RayTracingLightDataUniformBuffer': is not a member of 'FViewInfo'
```

Seems the API might have changed. Any chance of updating this to 5.4 or 5.5?

**Comment by mastercoms** [comment]
To clarify, this plugin isn't designed for functional use. The rendering isn't working. We can't provide support for fully upgrading the plugin as we don't use it anymore. It's only meant to provide people with an offramp for data cleanup from when NVIDIA dropped support for it a few versions back.

**Comment by avikbis** [comment]
Thanks for clarifying.

**Comment by GapingPixel** [comment]
Im no longer able to use RTXGI on an version of Unreal (4.27/5.0). Im not sure whats going on but it looks like a Windows update issue to me, since it was working fine for me on september 2024. Can anyone confirm ?
